# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: name-tests-test
        args: ['--django']
-   repo: https://gitlab.com/PyCQA/flake8
    rev:  3.7.9
    hooks:
    -   id: flake8
        args: [--max-line-length=120, --ignore=D100]
        additional_dependencies: [
            'flake8-string-format==0.2.3',
            'flake8-bugbear==20.1.4',
            'flake8-comprehensions==3.2.2',
            'flake8-eradicate==0.2.4',
            'flake8-quotes==2.1.1',
            'flake8-assertive==1.2.1',
            'flake8-deprecated==1.3',
            'flake8-docstrings==1.5.0',
            'flake8-isort==2.7.0',
            'flake8-pep3101==1.2.1',
            'flake8-print==3.1.4',
            'flake8-assertive==1.2.1',
            'pep8-naming==0.9.1',
        ]
