dist: focal
language: python

addons:
  apt:
    packages:
      - python-dev
      - libxml2-dev
      - libxmlsec1-dev

python:
  - 3.5

git:
  depth: false


services:
  - mongodb

cache:
  directories:
    - $HOME/edxapp_toxenv/
  pip: true

install:
  - pip install tox

env:
  global:
    # Avoid caching edx-platform's entry_points
    - TRAVIS_FIXES="pip install -r requirements/edx/local.in"
    - BOTO_CONFIG="/etc/nonexistent.cfg"

  jobs:
    - name=pep8
    - name=common-minimal
    - name=common
    - name=lms-1
    - name=lms-2
    - name=mte
    - name=studio

script: tox -e $TRAVIS_JOB_NAME

branches:
  # Reduce our TravisCI usage by skipping all pull request branches to reduce effect on the environment (earth),
  # so `continuous-integration/travis-ci/push` shouldn't be built anymore.
  only:
    - /^appsembler\/(tahoe|hawthorn)\/(develop|master)$/
    - appsembler/juniper-upgrade
