language: python
python:
  - "3.5"

services:
  - mongodb

node_js: 6

cache:
  directories:
    - $HOME/edxapp_toxenv/
  pip: true
  npm: true

before_install:
  - sudo rm -f /etc/boto.cfg
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install python-dev libxml2-dev libxmlsec1-dev

install:
  - pip install tox

env:
  global:
    # Avoid caching edx-platform's entry_points
    - TRAVIS_FIXES="pip install -r requirements/edx/local.in"

- jobs:
  include:
  - name: pep8
  - name: common-minimal
  - name: common
  - name: lms-1
  - name: lms-2
  - name: mte
  - name: studio

script: tox -e $TRAVIS_JOB_NAME

branches:
  # Reduce our TravisCI usage by skipping all pull request branches to reduce effect on the environment (earth),
  # so `continuous-integration/travis-ci/push` shouldn't be built anymore.
  only:
   - /^appsembler\/(tahoe|hawthorn)\/(develop|master)$/
   - appsembler/juniper-upgrade
