name: Check Python Dependencies

on:
  pull_request:

defaults:
  run:
    shell: bash # strict bash
    working-directory: ./scripts

jobs:
  check_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install requests module
        run: pip install requests

      - name: Install requests module
        run: pip install rich      

      - name: Make the script files executable
        run: chmod +x find_dependencies.py

      - name: Run Python script
        run: python find_dependencies.py edx-platform --org edx
  