name: Check Python Dependencies

on:
  pull_request:

defaults:
  run:
    shell: bash # strict bash

jobs:
  check_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Create repo_work directory        
        run: |
          WORK_DIR="/tmp/unpack_reqs"
          repo_name="${{ github.repository }}"
          repo_work="$WORK_DIR/$repo_name"
          mkdir -p "$repo_work"
          echo "$repo_work"
      
      - name: Copy Python requirements file
        run: |
          for req_file in "requirements/edx/base.txt" "requirements/base.txt" "requirements.txt"; do
            if [ -f "$req_file" ]; then
              cp "$req_file" /tmp/unpack_reqs/openedx/edx-platform/base.txt
              echo "Python requirements file found: $req_file"
              echo "Content of base.txt:"
              cat "$req_file"
              break
            fi
          done

      - name: Install requests module
        run: pip install requests

      - name: Install requests module
        run: pip install rich      

      - name: Make the script files executable
        run: chmod +x find_dependencies.py
        working-directory: ./scripts

      - name: Run Python script
        run: python find_dependencies.py edx-platform --org edx
        working-directory: ./scripts
  