name: Check Python Dependencies

on:
  pull_request:
    
defaults:
  run:
    shell: bash # strict bash

jobs:
  check_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Create repo_work directory
        run: mkdir -p WORK_DIR/repo_work

      - name: Copy Python requirements file
        run: |
          py_reqs=$(find . -maxdepth 1 -name "requirements*.txt" | head -n 1)
          if [ -f "$py_reqs" ]; then
            cp "$py_reqs" WORK_DIR/repo_work/base.txt
            echo "Python requirements file: $py_reqs"
            echo "Content of base.txt:"
            cat "$py_reqs"
          else
            echo "No Python requirements file found."
          fi