name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
    commitlint:
        uses: edx/.github/.github/workflows/commitlint.yml@master
    npm-lockfile-version-check:
        uses: edx/.github/.github/workflows/lockfileversion-check.yml@master
    js-tests:
        uses: .github/actions/js-tests.yml

