name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
    steps:
      - uses: actions/checkout@v2
      - name: Start container
        run: |
          docker-compose -f ./.github/docker-compose.yml.migrations up -d
      - name: Install dependencies
        run: |
          docker exec -t ecommerce_testing bash -c "
            cd /edx/app/ecommerce/ecommerce/ &&
            python3 -m pip install tox
          "
      - name: Run tests
        run: |
          docker exec -t -e CI=1 ecommerce_testing bash -c "
            cd /edx/app/ecommerce/ecommerce/ &&
            PATH=\$PATH:/edx/app/ecommerce/nodeenvs/ecommerce/bin:/snap/bin
            DJANGO_ENV=${{ matrix.django-env }} make ${{ matrix.targets }}
          "
      - name: Run coverage
        if: matrix.testname == 'test-python'
        run: |
          docker exec ecommerce_testing /edx/app/ecommerce/ecommerce/.ci/run_coverage.sh
      - name: Setup Python
        if: matrix.testname == 'test-python'
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: x64
      - name: Report coverage
        if: matrix.testname == 'test-python'
        run: |
          pip install codecov
          codecov
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: x64
      - name: Install Dependencies
        run: pip install -r requirements/docs.txt -r requirements/tox.txt
      - name: Build the docs
        run: make docs
