name: Quality checks

on:
  pull_request:
  push:
    branches:
      - master
      - open-release/lilac.master

jobs:
  run_tests:
    name: Quality Others
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        python-version:
          - '3.11'
        node-version: [ 18 ]

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Fetch base branch for comparison
      run: git fetch --depth=1 origin ${{ github.base_ref }}

    - name: Install Required System Packages
      run: sudo apt-get update && sudo apt-get install libxmlsec1-dev

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup npm
      run: npm i -g npm@8.5.x

    - name: Get pip cache dir
      id: pip-cache-dir
      run: |
        echo "::set-output name=dir::$(pip cache dir)"

    - name: Cache pip dependencies
      id: cache-dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.pip-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/edx/testing.txt') }}
        restore-keys: ${{ runner.os }}-pip-

    - name: Install Required Python Dependencies
      env:
        PIP_SRC: ${{ runner.temp }}
      run: |
        make test-requirements

    - name: Run Quality Tests
      env:
        TEST_SUITE: quality
        SCRIPT_TO_RUN: ./scripts/generic-ci-tests.sh
        PIP_SRC: ${{ runner.temp }}
        TARGET_BRANCH: ${{ github.base_ref }}
      run: |
        ./scripts/all-tests.sh

    - name: Save Job Artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Build-Artifacts
        path: |
          **/reports/**/*
          test_root/log/**/*.log
          *.log

    - name: Run ruff quality tests
      id: run-ruff
      run: |
        ruff check lms/djangoapps/ lms/envs/ lms/lib/ lms/tests.py \
          openedx/core/djangoapps/ openedx/core/djangolib/ openedx/core/lib/ openedx/core/tests/ \
          openedx/core/tests/ openedx/core/types/ openedx/features/ openedx/testing/ openedx/tests/ \
          cms common xmodule --preview


  # This job aggregates test results. It's the required check for branch protection.
  # https://github.com/marketplace/actions/alls-green#why
  # https://github.com/orgs/community/discussions/33579
  success:
    name: Ruff checks successful
    if: always()
    needs:
      - run-ruff
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        # uses: re-actors/alls-green@v1.2.1
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe
        with:
          jobs: ${{ toJSON(needs) }}
