# Run ShellCheck on PRs and master

# For more context, see:
# https://github.com/openedx/.github/blob/master/docs/decisions/0001-shellcheck.rst

name: ShellCheck

on:
  pull_request:
  push:
    branches:
    - master

permissions:
  contents: read

jobs:
  shellcheck:
    strategy:
      matrix:
        os: ["ubuntu", "macos"]
    #uses: openedx/.github/.github/workflows/shellcheck.yml@master
    uses: kdmccormick/openedx.github/.github/workflows/shellcheck.yml@kdmccormick/shellcheck-impl
    with:
      # For details on the meaning of each of these arguments, see:
      # https://githu.com/openedx/.github/blob/master/.github/workflows/shellcheck.yml
      exclude-patterns: "./*"
      operating-system: "${{ matrix.os }}"
      shellcheck-version: "v0.9.0"
      #shellcheck-options: ""
