name: Migrations check on MySql 57

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  check_migrations:
    name: check migrations
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        python-version: [ 3.8 ]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libxmlsec1-dev

    - name: Get pip cache dir
      id: pip-cache-dir
      run: |
        echo "::set-output name=dir::$(pip cache dir)"

    - name: Cache pip dependencies
      id: cache-dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/edx/development.txt') }}
        restore-keys: ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        pip install -r requirements/pip.txt
        pip install -r requirements/edx/development.txt
        pip uninstall -y mysqlclient
        pip install --no-binary mysqlclient mysqlclient
        pip uninstall -y xmlsec
        pip install --no-binary xmlsec xmlsec

    - name: Run Tests
      run: |
        echo "Running the CMS migrations."
        paver update_assets cms --settings=bok_choy
