name: Upgrade one Python dependency

on:
  workflow_dispatch:
     inputs:
       branch:
         description: 'Target branch to create requirements PR against'
         required: true
         default: 'master'
         type: string
       package:
         description: 'Name of package to upgrade'
         required: true
         type: string

defaults:
  run:
    shell: bash

jobs:
  upgrade-one-python-dependency-workflow:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out target branch
        uses: actions/checkout@v3
        with:
          ref: "${{ inputs.branch }}"

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Set up environment variables
        env:
          BASE_BRANCH: "${{ inputs.branch }}"
          PACKAGE: "${{ inputs.package }}"
        run: |
          echo "PACKAGE=$PACKAGE" >> "$GITHUB_ENV"

      - name: Run make upgrade-package
        run: |
          make upgrade-package package="$PACKAGE"

      - name: Make a commit
        run: |
          git diff

          PR_BRANCH="$GITHUB_ACTOR/upgrade-$PACKAGE-`git rev-parse --short=8 HEAD`"
          echo "PR_BRANCH=$PR_BRANCH" >> "$GITHUB_ENV"

          git checkout -b "$PR_BRANCH"
          git add requirements/
          git commit -m "feat: Upgrade Python dependency $PACKAGE" \
              -m "Commit generated by workflow \`$GITHUB_WORKFLOW_REF\`"

      - name: Make PR against branch
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          gh pr create --base "$BASE_BRANCH" --head "$PR_BRANCH" --fill --reviewer "$GITHUB_ACTOR" \
              --title "feat: Upgrade Python dependency $PACKAGE" \
              --body "@${GITHUB_ACTOR}: Here's the package upgrade you requested."
