name: verify unit tests count

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  collect-and-verify:
    if: (github.repository == 'edx/edx-platform-private') || (github.repository == 'openedx/edx-platform' && (startsWith(github.base_ref, 'open-release') == false))
    runs-on: [ "ubuntu-20.04" ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: install system requirements
        run: |
          sudo apt-get update && \
          sudo apt-get install --yes \
          build-essential git language-pack-en libmysqlclient-dev libssl-dev libxml2-dev \
          libxmlsec1-dev libxslt1-dev lynx xvfb pkg-config python3-dev python3-venv && \
          sudo rm -rf /var/lib/apt/lists/*

      - name: install requirements
        run: |
          sudo apt-get remove python3-blinker python3-commandnotfound python3-entrypoints \
          python3-parted python3-pexpect python3-pyasn1-modules python3-simplejson \
          python3-systemd python3-yaml ufw -y
          sudo make test-requirements

      - name: verify unit tests count
        uses: ./.github/actions/verify-tests-count
